galaxy_info:
  role_name: oneagent
  author: Kevin Holmes
  description: Deploy the Dynatrace OneAgent
  company: Red Hat and Dynatrace ISV Partnership
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  galaxy_tags: [dynatrace, oneagent, davis, ai, monitoring, cloud, application, tools, windows, linux]
dependencies: []
